### PR TITLE
added extra security policies

### PR DESCRIPTION
**Pull request by osimuka**

### CODE REVIEW

**Comment by osimuka** [comment]
This pull request consists of http header  configs that will increase the app service grade on [here] (https://securityheaders.com/) to around Grade C. Which should be good enough to what is need on the public webapp.

However we can look into this library [for http permission policy geared for Django apps](https://github.com/adamchainz/django-permissions-policy)

@chris-pettinga @nahmed99 let me know your thoughts

**Comment by chris-pettinga** [comment]
> This pull request consists of http header configs that will increase the app service grade on [here] (https://securityheaders.com/) to around Grade C. Which should be good enough to what is need on the public webapp.
> 
> However we can look into this library [for http permission policy geared for Django apps](https://github.com/adamchainz/django-permissions-policy)
> 
> @chris-pettinga @nahmed99 let me know your thoughts

Hey Uka, I think we should be aiming for A/A+ for the report on securityheaders.com. What are the current things holding us back?

**Comment by osimuka** [comment]
> 

I believe, once we add `Content-Security-Policy` and `Permissions-Policy` we can be able to get towards an A/A+

**Comment by chris-pettinga** [comment]
Looks good to me @osimuka, what's our grade now with this stuff implemented. Give me a call when free and I can show you how to deploy to Jenkins and force the environment to use the prod.py DJANGO_SETTINGS_MODULE

**Comment by osimuka** [comment]
> Looks good to me @osimuka, what's our grade now with this stuff implemented? Give me a call when free and I can show you how to deploy to Jenkins and force the environment to use the prod.py DJANGO_SETTINGS_MODULE

@chris-pettinga we can sort this today, but however we will need to merge the pull request and have it on `UAT` at least to test out the grade score as `https://securityheaders.com/` only accepts `https` domains , I just made sure it dosen't break normal functionality of the app, this was tested locally.

**Review by nahmed99 — APPROVED** [review]

**Pull request merged**
