### PR TITLE
Moving around CSS

### PR DESCRIPTION
**Pull request by chris-pettinga**
and sticking with the original system as we need SOME of the proto css even thouhg it's not strictly mean't for production.

Added fonts to their own file so future devs just need to copy the entire application.css file from the proto and put it in design.css

### CODE REVIEW

**Review by yusufsheiqh — APPROVED** [review]

**Comment by yusufsheiqh** [comment]
How do we ensure we only keep some of the CSS that is needed?

**Comment by chris-pettinga** [comment]
> How do we ensure we only keep some of the CSS that is needed?

I see it as it doesn't matter, i.e. it would take a fair amount of time and effort for a dev to figure out what's actually necessary and only put that stuff in a CSS file versus the overhead that a bulky CSS file gives us, does that make sense?

**Comment by yusufsheiqh** [comment]
> > How do we ensure we only keep some of the CSS that is needed?
> 
> I see it as it doesn't matter, i.e. it would take a fair amount of time and effort for a dev to figure out what's actually necessary and only put that stuff in a CSS file versus the overhead that a bulky CSS file gives us, does that make sense?

It makes sense, but we won't be able to fully know whether there are any security implications or accessibility issues as mentioned here: https://prototype-kit.service.gov.uk/docs/about

**Comment by osimuka** [comment]
> > > How do we ensure we only keep some of the CSS that is needed?
> > 
> > 
> > I see it as it doesn't matter, i.e. it would take a fair amount of time and effort for a dev to figure out what's actually necessary and only put that stuff in a CSS file versus the overhead that a bulky CSS file gives us, does that make sense?
> 
> It makes sense, but we won't be able to fully know whether there are any security implications or accessibility issues as mentioned here: https://prototype-kit.service.gov.uk/docs/about

There wouldn't be much security issues, from the compiled css, as the source is coming from our app, for the accessibility issue, I don't know if much has been expressed by users on not being able to access the pages.

**Comment by chris-pettinga** [comment]
I'm going to merge this now, if in the future we come across issues where proto CSS is causing issues with accessibility then we can split it up then, however now I think it's just unnecessary work to do it now.

**Pull request merged**
